### ISSUE TITLE
AxiosResponse interface not available from package to use as interface

### ISSUE THREAD

**Issue by cleeka** [nestjs/axios#100]

**Comment by nsssayom** [comment]
An additional _axios_  package needs to be installed to use this interface using  `npm install axios`. And that is not even mentioned in the doc.

**Comment by kamilmysliwiec** [comment]
Thanks for reporting. Updated docs 
![image](https://user-images.githubusercontent.com/23244943/127112205-d49b7fca-07c2-45de-b80c-8c681c6cf475.png)
