### ISSUE TITLE
Add ability to add types for data object in HttpService

### ISSUE THREAD

**Issue by kpervin** [nestjs/axios#1028]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently all methods of the HttpService take a `<T = any>` generic parameter, but type `data?; any`. It would be nice to enforce types on the data object that gets passed to either `AxiosRequestConfig` or the `data` parameter, respectively. This also allow it to be [compliant with the types that Axios themselves have in their library](https://github.com/axios/axios/blob/d844227411263fab39d447442879112f8b0c8de5/index.d.ts#L490-L497).

### Describe the solution you'd like

Retype the HttpService as follows:

```ts
import { AxiosInstance, AxiosPromise, AxiosRequestConfig, AxiosResponse } from "axios";
import { Observable } from "rxjs";

export declare class HttpService {
  protected readonly instance: AxiosInstance;
  constructor(instance?: AxiosInstance);
  request<T = any, D = any>(config: AxiosRequestConfig<D>): Observable<AxiosResponse<T>>;

  get<T = any, D = any>(url: string, config?: AxiosRequestConfig<D>): Observable<AxiosResponse<T>>;

  delete<T = any, D = any>(url: string, config?: AxiosRequestConfig<D>): Observable<AxiosResponse<T>>;

  head<T = any, D = any>(url: string, config?: AxiosRequestConfig<D>): Observable<AxiosResponse<T>>;

  post<T = any>(url: string, data?: any, config?: AxiosRequestConfig): Observable<AxiosResponse<T>>;
  post<T extends any, D extends any>(url: string, data: D, config?: AxiosRequestConfig<D>): Observable<AxiosResponse<T>>;

  put<T = any>(url: string, data?: any, config?: AxiosRequestConfig): Observable<AxiosResponse<T>>;
  put<T extends any, D extends any>(url: string, data: D, config?: AxiosRequestConfig<D>): Observable<AxiosResponse<T>>;

  patch<T = any>(url: string, data?: any, config?: AxiosRequestConfig): Observable<AxiosResponse<T>>;
  patch<T extends any, D extends any>(url: string, data: D, config?: AxiosRequestConfig<D>): Observable<AxiosResponse<T>>;

  get axiosRef(): AxiosInstance;
  protected makeObservable<T>(axios: (...args: any[]) => AxiosPromise<T>, ...args: any[]): Observable<AxiosResponse<T, any>>;
}
```

This way with overloading, if we provide the type then `data` becomes required.

### What is the motivation / use case for changing the behavior?

Just allowing the option to enforce stricter typing.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/axios/pull/1029
