### ISSUE TITLE
Add new Multipart Bodies methods from Axios

### ISSUE THREAD

**Issue by kpervin** [nestjs/axios#1030]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Axios currently has new [Multipart Bodies methods](https://axios-http.com/docs/multipart). Would be nice if the HttpService was able to access these.

### Describe the solution you'd like

[Add the following functions from the axios library.](https://github.com/axios/axios/blob/d844227411263fab39d447442879112f8b0c8de5/index.d.ts#L498-L500)

### What is the motivation / use case for changing the behavior?

Keeping up to date with the capabilities of the Axios library while still allowing for Observables.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/axios/pull/1031
