### ISSUE TITLE
Use class-transformer for json deserialization

### ISSUE THREAD

**Issue by juherr** [nestjs/axios#1045]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Instead of a plain json type, I'd like to have an object instance from the http response.

### Describe the solution you'd like

Just integrate `plainToInstance` before returning the response observable.

### What is the motivation / use case for changing the behavior?

The usecase is everywhere you want logic into classes.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
