### ISSUE TITLE
Update version Axios for 1.6.0 version

### ISSUE THREAD

**Issue by GiovanaNp1** [nestjs/axios#1052]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently axios has a moderate level vulnerability that without updating the lib @nestjs/axios we can only resolve it with npm audit fix --force, which is not a good practice

axios  1.0.0 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix --force`
Will install axios@1.6.7, which is outside the stated dependency range
node_modules/axios

<img width="230" alt="image" src="https://github.com/nestjs/axios/assets/34607779/f197948e-a817-4850-be56-38445ef460d0">

### Describe the solution you'd like

Update axios for version 1.6.0

### Teachability, documentation, adoption, migration strategy

https://github.com/advisories/GHSA-wf5p-g6vw-rhxx

### What is the motivation / use case for changing the behavior?

This modification is necessary because without it many applications are left with vulnerabilities, this affects all teams that use these libs

**Comment by micalevisk** [comment]
I guess that will be handled by Renovatebot soon

Also, since `axios` is a peer dependency of `@nestjs/axios` and the semver range is `^1.3.1`, you should be able to install that `1.6.0` in your side already.

**Comment by GiovanaNp1** [comment]
Thank you so much
