### ISSUE TITLE
Security issue: a dependency should be updated

### ISSUE THREAD

**Issue by didaquis** [nestjs/axios#1114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi. This repo use a dependency that use a dependency that contains a security issue. 

`@nestjs/axios@3.0.2 > axios@1.6.7 > follow-redirects@1.15.5`. 

Solve that security issue is easy, just updated to Axios 1.6.8  https://github.com/axios/axios/releases/tag/v1.6.8 

Details about the security issue: https://github.com/advisories/GHSA-cxjh-pqwp-8mfp 

### Minimum reproduction code

https://github.com/nestjs/axios

### Steps to reproduce

1. npm audit

### Expected behavior

I expect no contain any security issue on the dependencies of @nestjs/axios

### Package version

3.0.2

### NestJS version

10.3.9

### Node.js version

18.16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
axios is a peer dependency of `@nestjs/axios` so the upgrade can be done already by you. Just run `npm i axios@latest`

**Comment by didaquis** [comment]
Yes you're right. However, it is not efficient for thousands of people to update thousands of projects because `@nestjs/axios` distributes a version that depends on a library that contains a security issue that has a fix published months ago.

If I follow those instructions, my project will not have that security incident. But the rest of the projects that use `@nestjs/axios` will have it. However, if `@nestjs/axios` is updated, all those projects will receive the security patch.

I'm wrong?  🤔

**Comment by didaquis** [comment]
Oh, I understand what you want to tell me. Thank you

**Comment by micalevisk** [comment]
tbf since package manager install those peer deps for you automatically, you can just run `npm i` then you'll receive the latest version of `axios` as long as its versions satisfies the range of all the dependencies of your project
