### ISSUE TITLE
HttpModule multiple service instances using registerAsync and useExisting

### ISSUE THREAD

**Issue by Allakazan** [nestjs/axios#1120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I want to configure two or more HttpServices for use inside my module
So i made a bunch of submodules that does all inside my main module

api.auth.module.ts
```ts
import { HttpModule, HttpService } from '@nestjs/axios';
import { Module } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

export abstract class AuthHttpService extends HttpService {}

@Module({
  imports: [
    HttpModule.registerAsync({
      useFactory: (configSvc: ConfigService) => ({
        timeout: 10000,
        baseURL: configSvc.get<string>('auth.endpoints.auth')!,
      }),
      inject: [ConfigService],
    }),
  ],
  providers: [{ provide: AuthHttpService, useExisting: HttpService }],
  exports: [AuthHttpService],
})
export class AuthAPIModule {}

```

api.checkout.module.ts
```ts
import { HttpModule, HttpService } from '@nestjs/axios';
import { Module } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

export abstract class CheckoutHttpService extends HttpService {}

@Module({
  imports: [
    HttpModule.registerAsync({
      useFactory: (configSvc: ConfigService) => ({
        timeout: 10000,
        baseURL: configSvc.get<string>('checkout.endpoints.auth')!,
      }),
      inject: [ConfigService],
    }),
  ],
  providers: [{ provide: CheckoutHttpService, useExisting: HttpService }],
  exports: [CheckoutHttpService],
})
export class CheckoutAPIModule {}

```

api.module.ts
```ts
import { Module } from '@nestjs/common';
import { AuthAPIModule } from './modules/api.auth.module';
import { CheckoutAPIModule } from './modules/api.checkout.module';
import { ApiService } from './providers/api.service.provider';

@Module({
  imports: [AuthAPIModule, CheckoutAPIModule],
  providers: [ApiService ],
  exports: [ApiService ],
})
export class ApiModule {}
```

But when i do something like this on exporting the main module:

```ts
    console.log('checkout', checkoutHttpService.axiosRef.defaults.baseURL);
    console.log('auth', authHttpService.axiosRef.defaults.baseURL);
```

Both returns undefined.

If i configure everything with `HttpModule.register` instead of `HttpModule.registerAsync`, somehow it magically works. How can i make this work with  registerAsync ?

### Minimum reproduction code

https://gist.github.com/Allakazan/82619c8183ebdcb799db0e8493ffb1fb

### Expected behavior

I should be able to use registerAsync with dynamic modules that uses useExisting

### Package version

3.0.2

### NestJS version

8.0.0

### Node.js version

20.10.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
what do you mean by 'it works when using `.register`' exactly? have you hard coded the `baseURL` values in this case?

**Comment by Allakazan** [comment]
![image](https://github.com/nestjs/axios/assets/25016389/0c6ef234-22b3-4ab2-87af-e2f4b63f41c3)


Nevermind, it works with .registerAsync. 
I forgot to add my new config files to the ` ConfigModule.forRoot` method.
If you guys want to know to do it, [there is a great tutorial on dev.to](https://dev.to/micalevisk/nestjs-tip-how-to-inject-multiple-versions-of-the-same-provider-into-one-module-eg-many-axios-instances-5agc)

Sorry to open this issue without any real bug

> what do you mean by 'it works when using `.register`' exactly? have you hard coded the `baseURL` values in this case?

Yes i hardcoded to test it and it were working, i don't figured out it could be a problem with my config files setup
