### ISSUE TITLE
security issue in dependency

### ISSUE THREAD

**Issue by wtrzy** [nestjs/axios#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Performing `npm audit` returns security issue inside axios.

```
# npm audit 
# npm audit report

axios  >=1.3.2
Severity: high
Server-Side Request Forgery in axios - https://github.com/advisories/GHSA-8hc4-vh64-cxmj
fix available via `npm audit fix`
node_modules/axios

1 high severity vulnerability

To address all issues, run:
  npm audit fix
```

### Minimum reproduction code

https://github.com/advisories/GHSA-8hc4-vh64-cxmj

### Steps to reproduce

1. `npm audit`
2. `npm audit fix`
3. `npm audit`

### Expected behavior

`npm audit | grep "found 0 vulnerabilities"`

### Package version

3.0.2

### NestJS version

10.4.0

### Node.js version

20.12.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

VSCode devcontainer running Oracle Linux 8

**Comment by kiknaio** [comment]
Issue is related to Axios SSRF vulnerability. Here's more details on that https://security.snyk.io/vuln/SNYK-JS-AXIOS-7361793

**Comment by KieranMarienAppfoundry** [comment]
Anyone working on this or do I open a pr for this?

**Comment by paskaran** [comment]
We also facing issues in our Audit pipeline to.. Is there a fix planned ?

**Comment by KieranMarienAppfoundry** [comment]
> We also facing issues in our Audit pipeline too.. Is there a fix planned ?

https://github.com/axios/axios/pull/6539

We need to wait for this pr to merge.

**Comment by paskaran** [comment]
> > We also facing issues in our Audit pipeline too.. Is there a fix planned ?
> 
> [axios/axios#6539](https://github.com/axios/axios/pull/6539)
> 
> We need to wait for this pr to merge.

Thanks 😃

**Comment by KieranMarienAppfoundry** [comment]
> > > We also facing issues in our Audit pipeline too.. Is there a fix planned ?
> > 
> > 
> > [axios/axios#6539](https://github.com/axios/axios/pull/6539)
> > We need to wait for this pr to merge.
> 
> PR already merged 😀

Yup but they need to release it as V1.7.4. I assumed that would happen after the merge but i seems like there's issues with it. Cause it changes the way some things are handled(not spec compliant I believe). But they are working on a fix. 

https://github.com/axios/axios/issues/6463#issuecomment-2286538061. https://github.com/axios/axios/pull/6539#issuecomment-2286492862.

Once 1.7.4 the bot will automatically update it. (I think)

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/axios/pull/1173
