### ISSUE TITLE
Canceling/unsubscribing requests does not work if `config.cancelToken` is not set manually

### ISSUE THREAD

**Issue by russaa** [nestjs/axios#1217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If an `axios` request is started without setting the `AxiosRequestConfig.cancelToken` (and using that later to "manually" cancel it), the request is not actually cancelled when it's unsubscribed to.

The problem seems to be within the implementation of `HttpService.makeObservable()` when the `AxiosRequestConfig` is extracted from the arguments, see https://github.com/nestjs/axios/blob/e594fe92726f70b9684dc137028f082827b44c5b/lib/http.service.ts#L76

This actually creates a copy of the configuration object, so modifying it later (by adding a cancellation token) is only modifying the copy, and not the `args` variable that is used to invoke `axios` at 
https://github.com/nestjs/axios/blob/e594fe92726f70b9684dc137028f082827b44c5b/lib/http.service.ts#L84

### Minimum reproduction code

https://github.com/nestjs/axios/tree/3.0.3

### Steps to reproduce

1. create a subscription for a longer running query via the `HttpService` using `axios` (without specifying a `config` parameter)
2. unsubscribe
3. check server backend that request is actually cancelled shortly after unsubscribing

or print the arguments that the `axios` invocation actually receives (that is, the `axios` library) as debug output:  
you should notice, that there is actually no cancellation token (field `cancelToken`) in the used configuration for the request.

### Expected behavior

unsubscribing to a request should actually cancel the request at the backend.

This could be accomplished by not using a copy for the configuration object (and updating the `args` variable if necessary), e.g. replacing https://github.com/nestjs/axios/blob/e594fe92726f70b9684dc137028f082827b44c5b/lib/http.service.ts#L76

with something like:
```ts
let config: AxiosRequestConfig = args[args.length - 1];
if(!config) {
     args[args.length - 1] = config = {};
}
```

### Package version

3.0.2

### NestJS version

10.3.7

### Node.js version

20.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/axios/commit/dcbc1022728d608b49573a578089faae8a91501b
