### ISSUE TITLE
Retry with given config leads to CanceledError

### ISSUE THREAD

**Issue by trochol** [nestjs/axios#1232]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

commit dcbc102

### Versions

3.0.3 -> 3.1.0

### Describe the regression

With the bugfix for the following issue a new bug was introduced:
https://github.com/nestjs/axios/issues/1217
Before the given config was cloned with the spread operator.
In the bugfix the config was taken as is and the `AxiosRequestConfig.cancelToken` was added if there was none in the config.

Now, if you are using the rxjs retry and pass a config without CancelToken, the given config will be extended with the default CancelToken.
And if the request fails the retry subscribes again to observable with the original config, which then has a fulfilled CancelToken of the first try.

### Minimum reproduction code

https://github.com/trochol/axios-retry/tree/main

### Expected behavior

The retry operator should be able tosubscribe to the observable and a new CancelToken shall be added to the config.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by trochol** [comment]
In my opinion I would revert the commit of PR #1217.
The CancelToken includes a promise, which leads to the cancel, when fulfilled.
The caller can pass an own promise and resolve it whenever he needs to.
So why should it be possible to manipulate the config, after it has been passed to axios?

**Comment by trochol** [comment]
Sorry, now I saw the main problem of PR #1217.
It's not the possibility to manually add the CancelToken later.
The problem is that the config copy was extended but never passed to axios.
Then I can create a PR to fix my problem and keep the other issue in mind.
But I will create a copy of the config again, so manually setting the CancelToken after creating the observable won't be possible.

**Comment by trochol** [comment]
Thanks for merging the PR @kamilmysliwiec!

**Comment by tobiasschweizer** [comment]
Thanks for this!
