### ISSUE TITLE
How do I register the axios httpmodule module globally?

### ISSUE THREAD

**Issue by PanHywel** [nestjs/axios#214]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

How do I register the axios httpmodule module globally?

### Describe the solution you'd like

```ts
@Module({
  imports: [
    HttpModule.register({
      timeout: 5000,
      maxRedirects: 5,
      httpsAgent: new Agent({
        rejectUnauthorized: false
      }),
      transformResponse: [
        function (data) {
          // Dols whatever you want to transform the data
          return _json.parse(data);
        }
      ]
    })
  ],
  providers: [RequestService],
  exports: [RedisService]
})
expor
```

### What is the motivation / use case for changing the behavior?

Easy to call

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
