### ISSUE TITLE
Enable default axios mode with promises instead of observables

### ISSUE THREAD

**Issue by kubal5003** [nestjs/axios#271]
### Is there an existing issue that is already proposing this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm trying to use axios as explained in [axios documentation](https://github.com/axios/axios) but instead I'm getting `Observable`s instead of plain old promises from `HttpService`.

### Describe the solution you'd like

I would like to have the choice whether I want to use promise or observable based API for axios.

### What is the motivation / use case for changing the behavior?

I don't think I should be forced to use axios with only observables, because that is not how axios was built and not how it operates. Maybe there should be separate packages for axios with observables and with promises? 

Not sure if you're aware but there is a package `axios-observable` that does a similar thing with its `createObservable` vs your implementation of `makeObservable`.

**Comment by micalevisk** [comment]
I don't believe this will change.

Here's a alternative packate to `@nestjs/axios` that doesn't uses observables https://github.com/benhason1/nestjs-http-promise

**Comment by micalevisk** [comment]
you can access the underlying axios instance using `this.httpService.axiosRef()` btw

https://github.com/nestjs/axios/blob/dc0601dfe8b3d7fd191a96abe96835e65af02b8a/lib/http.service.ts#L67-L69

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
