### ISSUE TITLE
Align Version Number with other NestJS packages (8.x.x) instead of (0.0.3)

### ISSUE THREAD

**Issue by Kr0san89** [nestjs/axios#274]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It is not really a big issue but, as you give already deprecation warnings for the old version
`DEPRECATED! "HttpModule" (from the "@nestjs/common" package) is deprecated and will be removed in the next major release. Please, use the "@nestjs/axios" package instead.`
I think it would be best to align version numbers to the other nestjs packages
1. because 0.0.X -> always looks a little bit like not "fully" ready
2. because ther packages of nestjs always align with major version number.

### Describe the solution you'd like

bump the version to 8.x.x

### What is the motivation / use case for changing the behavior?

.

**Comment by kamilmysliwiec** [comment]
We'll eventually bump the version to 8
