### ISSUE TITLE
Publish a new version with newest axios

### ISSUE THREAD

**Issue by maurolucc** [nestjs/axios#279]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Latest published version of https://github.com/nestjs/axios still relies on axios 0.23.0. 

### Describe the solution you'd like

Publish a new version, since the master branch already [supports 0.24.0](https://github.com/nestjs/axios/blob/master/package.json#L21).

### What is the motivation / use case for changing the behavior?

Be able to update nestjs and axios.

**Comment by kamilmysliwiec** [comment]
Published

**Comment by maurolucc** [comment]
Thanks for the quick reply.
