### ISSUE TITLE
Set axios@0.25.0 as minimum required version

### ISSUE THREAD

**Issue by TrumanRu** [nestjs/axios#320]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

0.0.1 -> 0.0.5

### Describe the regression

axios@0.25.0 is recommended version only.

Another package (@keycloak/keycloak-admin-client@16.1.0) uses axios@^0.24.0 as minimum minor required version.
In result i've had @nestjs/axios@0.0.5 and axios@0.24.0 installed. But it raises TypeScript compilation error:
```
Type 'Promise<import(".../node_modules/@nestjs/axios/node_modules/axios/index").AxiosResponse<any, any>>' is not assignable to type 'Promise<import(".../node_modules/axios/index").AxiosResponse<any, any>>'
(bla-bla-bla)
```

### Minimum reproduction code

```ts
get(url: string): Promise<AxiosResponse> {
    return lastValueFrom(
      this.httpService.get(url)
    );
  }
```

### Expected behavior

Minimum axios@0.25.0 installes by default with `npm install` command

**Comment by kamilmysliwiec** [comment]
> axios@0.25.0 is recommended version only.

This is the expected behavior. You can always install the older version of the `@nestjs/axios` package if needed.
