### ISSUE TITLE
Publish a new version with the latest Axios

### ISSUE THREAD

**Issue by stephenwade** [nestjs/axios#336]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The latest release of nestjs/axios depends on axios 0.25.0. The latest Axios version is 0.26.0.

### Describe the solution you'd like

Publish a new version, since the master branch already [depends on 0.26.0](https://github.com/nestjs/axios/blob/master/package.json#L21).

### What is the motivation / use case for changing the behavior?

I want to use the latest version of Axios.

**Comment by kamilmysliwiec** [comment]
Just published
