### ISSUE TITLE
Add AxiosError Interface to package export

### ISSUE THREAD

**Issue by leguellec** [nestjs/axios#405]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I will be easier to expose AxiosError type (like for AxiosResponse https://github.com/nestjs/axios/issues/100), it will avoid installing axios package 

### Describe the solution you'd like

Add AxiosError in 

``` javascript
import Axios, {
  AxiosInstance,
  AxiosPromise,
  AxiosRequestConfig,
  AxiosResponse,
  CancelTokenSource,
} from 'axios';
```

in this httpservice file https://github.com/nestjs/axios/blob/master/lib/http.service.ts
And export it, or in interfaces/HttpModule.interface

### Teachability, documentation, adoption, migration strategy

After this part `AxiosResponse is an interface exported from the axios package ($ npm i axios).` in https://docs.nestjs.com/techniques/http-module whe cousl add this : `We also expose AxiosError to ease error type handling`

We may also remove the fact that we need to install axios package as it's a dependency, and already installed

### What is the motivation / use case for changing the behavior?

We handle error on dependency service calls, and depending on response we handle it with a try / cacth and with TS 4.4 changes, we would like to do something like

``` javascript
catch(error: unknown) {
  if (error  instanceOf AxiosError) {
       switch (error?.response?.status) {
          case 404:
             return []
           case 400:
              throw new CompanyIdInvalid('Company not found', path);
     }
  }
}
```

**Comment by Birdland998** [comment]
who know how to fix this error - AxiosError: Request failed with status code 403

**Comment by micalevisk** [comment]
@Birdland998 I'm pretty sure your issue isn't related to NestJS. Please report issues on `axios` on their side, instead: https://github.com/axios/axios

**Comment by Birdland998** [comment]
> @Birdland998 I'm pretty sure your issue isn't related to NestJS. Please report issues on `axios` on their side, instead: https://github.com/axios/axios

Thank you
