### ISSUE TITLE
出现tcp connect时间过长的问题，导致接口响应缓慢

### ISSUE THREAD

**Issue by xinandiyishuai** [nestjs/axios#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![1655688246653](https://user-images.githubusercontent.com/26061804/174509637-50669d92-462f-4f14-99f9-a64f756d8cd4.jpg)

### Minimum reproduction code

no

### Expected behavior

服务运行一段时间之后会出现该问题，接口响应时间随运行时间而变长
![1655688606698](https://user-images.githubusercontent.com/26061804/174510064-e8a5840b-f64e-4635-bef3-706529a24005.jpg)

### Package version

0.0.7

### NestJS version

8.0.0

### Node.js version

14.17.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
