### ISSUE TITLE
Support for axios interceptors

### ISSUE THREAD

**Issue by brunosilvacarvalho** [nestjs/axios#515]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Since the axios instance is inside the module there is no easy way to add axios interceptors on the instance. Many workarounds suggested rely on the use of onModuleInit of the module which imports the HttpModule, but this aprouch breaks when the service is used on a injectable with scope REQUEST, because onModuleInit only add the interceptor on the first instance generated and not the others instances generated by scope Request.

### Describe the solution you'd like

Expand HttpModuleOptions to add interceptors on the config of the module and add it to the axios instance generated by the module.

### What is the motivation / use case for changing the behavior?

Allowing the configuration of interceptors on the axios instance of the http module, i can generate interceptors to add authorization headers, add logging, add metrics, etc. This reduces the amount of times that i had to make wrappers around the module and the service in other to achieve desired behaviors which comes with axios.

**Comment by kamilmysliwiec** [comment]
If you look at the source code, you'll see that this is a very tiny package (minimal abstraction layer on top of axios). If you need more flexibility, you can simply fork it and align with your needs.
