### ISSUE TITLE
Upgrade to Axios major 1.x

### ISSUE THREAD

**Issue by alex-lighthouse** [nestjs/axios#580]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hello! Is there any plan of supporting axios 1.x soon? People are discussing here that updating axios from 0.27.2 to latest 1.x is breaking: https://github.com/axios/axios/issues/5100

### Describe the solution you'd like

Migrate to axios 1.x

### What is the motivation / use case for changing the behavior?

NestJS projects will be stuck on 0.x as long as 1.x is not properly supported here

**Comment by jmcdo29** [comment]
A 1.x upgrade is coming. Until then, [as our dependencies say](https://github.com/nestjs/axios/blob/master/package.json#L22), 0.27.2 should be used. 

[Renovate already created a PR for this as well](https://github.com/nestjs/axios/pull/572) and we'll have to fix up whatever breaking changes there are and _probably_ publish under a new major version

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/axios/pull/572
