### ISSUE TITLE
Allow the HttpModule to register headers with the HeadersDefaults type 

### ISSUE THREAD

**Issue by befabry** [nestjs/axios#621]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Axios allows to define "common" headers. It is not possible to register common headers through the `HttpModule.register` method.

For instance :

When invoking the httpService, it is possible to add a value to the `common` headers such as :

`this.httpService.axiosRef.defaults.headers.common['Authorization'] = axiosResponse.headers.authorization ?? '';`

But it is not possible to register the same kind of headers through the `HttpModule.register` method :

    HttpModule.register({
      headers: {
        common: { 'Content-Type': 'application/json', Accept: 'application/json' },  // => TS Error
        // 'Content-Type': 'application/json',
        // Accept: 'application/json',
      },
    }),

By removing the comments it works though, Axios seems to pick them up. But it seems to be less granular.

### Describe the solution you'd like

Updating the AxiosRequestConfig such as

    export interface AxiosRequestConfig<D = any> {
      //Removed code
      headers?: AxiosRequestHeaders | Partial<HeadersDefaults>;
    }

It would allow the flexibility to set up the headers how we see fit while keeping the the actual way of doing things.

### What is the motivation / use case for changing the behavior?

A more granular declaration of the headers through the register method that follow the AxiosDefaults deinition

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
