### ISSUE TITLE
Axios needs to be updated to 1.2.x

### ISSUE THREAD

**Issue by ctsstc** [nestjs/axios#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Right now `axios.isAxiosError` will return the following error:

```
TypeError: Cannot read properties of undefined (reading 'isAxiosError')
```

There is a ticket around this in the axios repository here:
- https://github.com/axios/axios/issues/5011
- https://github.com/axios/axios/issues/5011#issuecomment-1301973128
- https://github.com/axios/axios/issues/5011#issuecomment-1355707228

The problem is fixed by updating axios to 1.2.x

Currently if I update and include axios by hand then I get version missmatching on my typing as explained here: 

- https://github.com/axios/axios/issues/5011#issuecomment-1355707228

> `Argument of type 'import("./node_modules/axios/index").AxiosRequestConfig<any>' is not assignable to parameter of type 'import("./node_modules/@nestjs/axios/node_modules/axios/index").AxiosRequestConfig<any>'.`

### Minimum reproduction code

https://github.com/axios/axios/issues/5011

### Expected behavior

I should be able to call `axios.isAxiosError` without it saying that axios is undefined.

This is a known bug for axios v1.1.3, and thus axios should be updated to 1.2.x

### Package version

1.0.0

### NestJS version

9.2.1

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/axios/pull/616
