### ISSUE TITLE
Make it easier to use axios types

### ISSUE THREAD

**Issue by stevenhair** [nestjs/axios#639]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Axios frequently updates its types, which can make upgrades difficult. Even the types between patch versions can be incompatible (the `AxiosRequestConfig` interfaces are not compatible between versions 1.2.1 and 1.2.2, for example). If you have another library that depends on axios, you can easily end up with a version in the root of node_modules that is incompatible with @nestjs/axios. Given how many of the axios types are exposed by @nestjs/axios, this can lead to confusing error messages.

The best way to mitigate this issue is to explicitly install axios in your project, but that doesn't completely solve the issue because you have to ensure that the version that you install is compatible with the one in @nestjs/axios.

### Describe the solution you'd like

There are two solutions that I can think of:

1. Set axios as a peer dependency. Since you need axios in the root of your node_modules to use the many types exposed by @nestjs/axios (e.g. `AxiosResponse`, `AxiosRequestConfig`, etc.) and you can't use this package without using the axios types (unless your Typescript config is relatively loose), this seems fair to me. It will also ensure that the axios version in the root is the correct one. I don't believe that there are any drawbacks to this because you can't install an incompatible version of axios right now anyway unless you ignore the type incompatibilities. Since npm also installs peer dependencies automatically now, consumers of this package wouldn't need to explicitly specify an axios version in their package.json file.
2. Expos the axios types in this package. While this would work and potentially be less intrusive than the peer dependency, it's a bit clunky and would significantly increase the number of exports from this package. Re-exporting could be limited to just the types exposed by @nestjs/axios, but it might be difficult to determine which types are exposed and to maintain those exports. This is similar to #100 and #405 

### Teachability, documentation, adoption, migration strategy

For option 1, no changes would be required for use - imports would come from `axios` as they do today. For a few cases, users might be confused on installation when they have a version of axios that is not compatible. However, I think that npm explicitly informing users of an incompatible peer dependency is a better solution than the cryptic type errors that you receive at the moment (e.g. "AxiosRequestConfig is not compatible with AxiosRequestConfig").

For option 2, users would need to change all imports of axios types to come from this package. For example, `import { AxiosResponse } from 'axios'` would become something like `import { AxiosResponse } from '@nestjs/axios'`. A note should also be added to the documentation if this is the chosen option.

### What is the motivation / use case for changing the behavior?

The current behavior is confusing and occasionally frustrating and the TypeScript error messages aren't very helpful. This would reduce friction when upgrading packages and would prevent confusing error messages.

**Comment by Markus-Ende** [comment]
for now, you could import it like this: `import { AxiosResponse  } from '@nestjs/axios/node_modules/axios';`.

A bit ugly, but it works ;-)

**Comment by svyatoslavratov** [comment]
Same problem

**Comment by svyatoslavratov** [comment]
Same problem.

I'm getting error TS2742 when using `import { AxiosResponse  } from '@nestjs/axios/node_modules/axios'`

> for now, you could import it like this: `import { AxiosResponse } from '@nestjs/axios/node_modules/axios';`.
> 
> A bit ugly, but it works ;-)

**Comment by kamilmysliwiec** [comment]
I'm going to move axios to peerDependencies

**Comment by stevenhair** [comment]
This has already been released as 2.0.0. The change was made in d3d8a4ae098bca11a28186afe5d42c09f938eab3.
