### ISSUE TITLE
Current axios version used 1.2.1 has Bug with Brotli, bump needed to 1.2.2

### ISSUE THREAD

**Issue by vitalyiegorov** [nestjs/axios#641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This could happen when you perform request to 3rd party service which supports Brotli compression https://github.com/axios/axios/issues/5346

### Minimum reproduction code

https://github.com/axios/axios/issues/5346

### Steps to reproduce

Any http request to 3rd party like instagram/facebook api will return `Error: unexpected end of file`

### Expected behavior

Successful response

### Package version

1.0.1

### NestJS version

8.1.3

### Node.js version

16.18.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/axios/pull/632
