### ISSUE TITLE
Nest v8 Support - Update of axios dependency to at least v1.2.2

### ISSUE THREAD

**Issue by NicoAiko** [nestjs/axios#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Like explained in https://github.com/axios/axios/issues/5346 and also in https://github.com/nestjs/axios/issues/641 there is a problem with v1.2.1 of the axios package. Unfortunately there hasn't been a version bump that's usable for projects that still use Nest v8.
We can't currently upgrade to Nest v9, so it would be fantastic, if there was a bump in the dependency version.

### Minimum reproduction code

-

### Expected behavior

Should be able to use the httpService without the above mentioned bug.

### Package version

1.0.1

### NestJS version

8.4.7

### Node.js version

16.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Not sure if I'm following. You just need to upgrade the underlying axios package without upgrading Nest - is that correct? If so, check out this link https://stackoverflow.com/questions/52416312/npm-equivalent-of-yarn-resolutions
