### ISSUE TITLE
this library does not support Nestjs 10.0.0

### ISSUE THREAD

**Issue by xuegao-tzx** [nestjs/axios#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

this library does not support Nestjs 10.0.0

### Minimum reproduction code

this library does not support Nestjs 10.0.0

### Expected behavior

this library does not support Nestjs 10.0.0

### Package version

2.0.0

### NestJS version

10.0.0

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

### Other

this library does not support Nestjs 10.0.0

**Comment by micalevisk** [comment]
looks like `@nestjs/axios@3` does, see: 

![image](https://github.com/nestjs/axios/assets/13461315/28d76008-5f6d-466f-958a-cc079238e8b4)
