### ISSUE TITLE
Provide optional payload in delete request

### ISSUE THREAD

**Issue by teaglebuilt** [nestjs/axios#856]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

[HTTP Wiki](https://en.wikipedia.org/wiki/HTTP#Request_methods) states that the **DELETE** method should have an optional payload. Why is this not the case?

### Describe the solution you'd like

add data: {}` as a optional argument to delete method.

### What is the motivation / use case for changing the behavior?

Write now, i cannot use this library to delete a resource from the api.

**Comment by micalevisk** [comment]
https://github.com/nestjs/axios/blob/f1712bdd059cdf707d2de2c9a99efc5549b1f5b1/lib/http.service.ts#L29-L33

as you can see above, the options are from `axios`. Please, report it to them. `npm docs axios`
